name: Deploy updated mirror list to GitHub pages

on:
  push:
    branches:
      - trunk
  workflow_dispatch:
  schedule:
    - cron: '37 1,4,7,10,13,16,19,22 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Get mirror state
        run: |
          podman run ghcr.io/zauguin/get-tl-mirror-status:get-tl-mirror-status mirrors > mirrors.json
      - name: Generate schema
        run: |
          podman run ghcr.io/zauguin/get-tl-mirror-status:get-tl-mirror-status schema > schema.json
      - name: Generate older 'us' file
        run: |
          jq -r 'map_values(map_values(to_entries | map(.value.url = .key | .value) | [.[] | select(.status == "Alive")] | if length == 0 then [] else group_by(.texlive_version) | INDEX(.[0].texlive_version) | map_values(group_by(.revision) | INDEX(.[0].revision) | map_values(map(.url))) | to_entries | max_by(.key | tonumber).value | to_entries | max_by(.key | tonumber).value end)) | .["North America"].USA | .[]' < mirrors.json > us
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
